---
# vars file for website
apache_log_dir: /var/log/apache2
apache_sites_dir: /etc/apache2/sites-available
gitlab_host: gabon.gitlab.com
gitlab_ssh_key_file: "${HOME}/.ssh/gabon.deployment@eia-global.org"
local_repo: "/var/www/{{ WEBSITE_DOMAIN }}" # TODO: Change this
# remote_repo: "" # Defined in inventory
# www_document_root: # defined in inventory
baseline_packages:
  - composer
  - nodejs
  - php7.3
  - php7.3-bcmath
  - php7.3-cli
  - php7.3-common
  - php7.3-ctype
  - php7.3-dom
  - php7.3-gd
  - php7.3-json
  - php7.3-mbstring
  - php7.3-opcache
  - php7.3-pgsql
  - php7.3-readline
  - php7.3-zip
  - php7.3-xml
  - software-properties-common
