DB_CONNECTION: "{{ TEST_DB_CONNECTION }}"
DB_DATABASE: "{{ TEST_DB_DBNAME }}"
DB_HOSTNAME: "{{ TEST_DB_HOSTNAME }}"
DB_PASSWORD: "{{ TEST_DB_PASSWORD }}"
DB_PORT: "{{ TEST_DB_PORT }}"
DB_USERNAME: "{{ TEST_DB_USERNAME }}"
www_document_root: "{{ local_repo }}/public"
remote_repo: "git@{{ gitlab_host }}:eia-global/transportapps/gabonweb.git"
WEBSITE_APP_NAME: "Gabon"
WEBSITE_APP_TITLE: "Gabon - Test Server"
WEBSITE_DEPLOYMENT_COMMIT: "develop"
WEBSITE_DOMAIN: "gabon-tst.globalorigin.org"
JWT_SECRET: "{{ TEST_JWT_SECRET }}"
REDIS_HOST: "{{ TEST_REDIS_HOST }}"
REDIS_PASSWORD: "{{ TEST_REDIS_PASSWORD }}"
REDIS_PORT: "{{ TEST_REDIS_PORT }}"
