# Make sure python is installed on all machines
all:
  hosts:
    wwwgabon-test:
      ansible_host: 3.232.106.185
      ansible_port: 22
      ansible_user: ubuntu
      become: true
    wwwgabon-dev:
      ansible_host: 3.232.106.185
      ansible_port: 22
      ansible_user: ubuntu
      become: true
    wwwgabon-prod:
      ansible_host: 18.233.143.37
      ansible_port: 22
      ansible_user: ubuntu
      become: true
  children:
    debians:
      hosts:
        wwwgabon-dev:
        wwwgabon-test:
        wwwgabon-prod:
    apaches:
      hosts:
        wwwgabon-dev:
        wwwgabon-test:
        wwwgabon-prod:
    websites:
      hosts:
        wwwgabon-dev:
        wwwgabon-test:
        wwwgabon-prod:
